name: Database Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v2 

      - name: Download dependencies
        run: mvn dependency:go-offline

      - name: Database Testing
        run: mvn test -Dtest=SchemaTests,StoreProcedureTests,TriggerTests

      - name: Generate HTML REPORT FROM SUREFIRE_REPORTS
        run: mvn surefire-report:report-only
        continue-on-error: true

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: HTML-REPORT
          path: target/site/
